# Site settings
title: Nanae Blog
description: ‘追求极致，用力过猛’
url: 'http://nanaezheng.me'
baseurl: '/nanaeblog/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: ‘nanaezheng’

author:
  name: ’Nanae Zheng’
  email: nanaezheng@gmail.com
  twitter_username: nanaezheng
  facebook_username: nanaezheng
  github_username:  nanaezheng
  #linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
